### ISSUE TITLE
🦂 [Bug] Discs of Norgannon event incomplete

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1188]
## 🦂 Bug report - Dungeon
- Lore Keeper of Norgannon NPC is missing text (broadcast_text with entry 3172) when you speak with him.
![image](https://user-images.githubusercontent.com/8654362/117382540-07fea100-aedf-11eb-8a29-d5f28795a258.png)
- When you speak with him, holograms of both a Dwarf (gobject 170353) and a Trogg (gobject 142488) should appear at some point, they aren't appearing (they need to be activated on gossip option select).
- Ancient Treasure chest is missing in the Hall of the Crafters. <https://classic.wowhead.com/object=141979/ancient-treasure>
- The Lore Keeper should only spawn when you accept the quest of the platinum discs.
- Not sure about this one but seems like the follow-up quest window appears instantly according to the English version of the video I link below, here in vMaNGOS you need to click the discs again.

Sniffed data about the chest:
```
         guid: 94252
           id: 141979
          map: 70
      zone_id: 1337
      area_id: 1337
   position_x: 153.39
   position_y: 289.091
   position_z: -52.2262
  orientation: 2.68781
    rotation0: 0
    rotation1: 0
    rotation2: 0.97437
    rotation3: 0.224951
 is_temporary: 0
 creator_guid: 0
   creator_id: 0
 creator_type: 
   display_id: 1387
        level: 0
      faction: 0
        flags: 0
dynamic_flags: 0
path_progress: 65535
        state: 1
         type: 3
       artkit: 0
 custom_param: 0
     sniff_id: 199
  sniff_build: 36325

```

Full event is visible here (in Spanish, couldn't find an English version): <https://youtu.be/_Cx7R3gM6Vk?t=718>

EDIT: English version (although incomplete, chest is not visible there): <https://www.youtube.com/watch?v=pHNxfOGPmwA>
