### ISSUE TITLE
There are two server record in realmd.realmlist, but client only show the first one.

### ISSUE THREAD

**Issue by xujintao** [vmangos/core#215]
**Current behavior**: 
Client realmlist only show Classic Beta 1
**Expected behavior**: 
Client realmlist show 2 rows.

**Steps to reproduce**:
Two mangosd hare the same db.

1. realmd.realmlist table
```
mysql> select * from realmlist \G
*************************** 1. row ***************************
                  id: 1
                name: Classic Beta 1
             address: 192.168.0.101
        localAddress: 127.0.0.1
     localSubnetMask: 255.255.255.0
                port: 8085
                icon: 1
          realmflags: 0
            timezone: 1
allowedSecurityLevel: 0
          population: 0.02
       gamebuild_min: 0
       gamebuild_max: 0
                flag: 2
         realmbuilds: 5875 6005 6141 
*************************** 2. row ***************************
                  id: 2
                name: Classic Beta 2
             address: 192.168.0.101
        localAddress: 127.0.0.1
     localSubnetMask: 255.255.255.0
                port: 8086
                icon: 1
          realmflags: 0
            timezone: 5
allowedSecurityLevel: 0
          population: 0
       gamebuild_min: 0
       gamebuild_max: 0
                flag: 2
         realmbuilds: 
2 rows in set (0.00 sec)
```
2. realmd start log
```
Core revision: 5166b62b5cc86db1b8f7 / 2019-06-13 19:00:36 +0300 / Linux_x64 (little-endian) [realm-daemon]
<Ctrl-C> to stop.

Using configuration file /vmangos/etc/realmd.conf.
Database: vmgdb;3306;root;*;realmd
Added realm "Classic Beta 1"
Added realm "Classic Beta 2"
```

**Client version**: 1.12.1

**Commit hash**: 5166b62

**Operating system**: ubuntu
